import { SECRET_STRAVA_CLIENT_ID, SECRET_STRAVA_CLIENT_SECRET, SECRET_STRAVA_REDIRECT_URI, SECRET_STRAVA_RESPONSE_TYPE, SECRET_STRAVA_SCOPE } from '../secrets';

export const STRAVA_CLIENT_ID = SECRET_STRAVA_CLIENT_ID;
export const STRAVA_CLIENT_SECRET = SECRET_STRAVA_CLIENT_SECRET;
export const STRAVA_REDIRECT_URI = SECRET_STRAVA_REDIRECT_URI;
export const STRAVA_RESPONSE_TYPE = SECRET_STRAVA_RESPONSE_TYPE;
export const STRAVA_SCOPE = SECRET_STRAVA_SCOPE;
